### ISSUE TITLE
MD5秒传

### ISSUE THREAD

**Issue by txcname** [izhangzhihao/FileUpload.Java#21]
请问，此示例中，MD5秒传的校检是在，所有文件块上传之后再进行验证的。所以应该是在上传之前，那么有一个问题是，在上传之前如何获取MD5的值。

**Comment by izhangzhihao** [comment]
上传之前是js读取文件获得md5值的

**Comment by izhangzhihao** [comment]
你可以详细看看代码和注释，里面有写

**Comment by txcname** [comment]
`
                uploader.md5File(file)
                        .then(function (fileMd5) { // 完成
                            //var end = +new Date();
                            // console.log("before-send-file  preupload: file.size="+file.size+" file.md5="+fileMd5);
                            //insertLog("<br>" + moment().format("YYYY-MM-DD HH:mm:ss") + " before-send-file  preupload:计算文件(" + file.name + ")MD5完成. 耗时  " + (end - start) + '毫秒  fileMd5: ' + fileMd5);
                            file.wholeMd5 = fileMd5;//获取到了md5
                            uploader.options.formData.md5value = file.wholeMd5;//每个文件都附带一个md5，便于实现秒传
                            $.ajax({//向服务端发送请求
                                cache: false,
                                type: "post",
                                //dataType: "json",
                                url: "defectController/IsMD5Exist",//baseUrl +
                                data: {
                                    fileMd5: fileMd5,
                                    fileName: file.name,
                                    fileID: file.id,
                                    //isShared: $("#isShared").val()
                                },`


是这部分代码。　　　
then　函数是在上传完成z才会执行。
在　FirBug 里面查看，是先发送上传的请求，最后发送这个IsMD5Exist请求的。


上传请求里面：
 参数里面确实没有MD5：

源代码
-----------------------------2455454191951
Content-Disposition: form-data; name="guid"

wu_1ba3qovkb13cr1kbe1p0fv310tp4
-----------------------------2455454191951
Content-Disposition: form-data; name="id"

WU_FILE_0
-----------------------------2455454191951
Content-Disposition: form-data; name="name"

1010.zip
-----------------------------2455454191951
Content-Disposition: form-data; name="type"

application/octet-stream
-----------------------------2455454191951
Content-Disposition: form-data; name="lastModifiedDate"

Sat Oct 10 2015 10:22:18 GMT+0800
-----------------------------2455454191951
Content-Disposition: form-data; name="size"

430577793
-----------------------------2455454191951
Content-Disposition: form-data; name="chunks"

42
-----------------------------2455454191951
Content-Disposition: form-data; name="chunk

ｍｄ５
的值。

**Comment by izhangzhihao** [comment]
我不清楚你看的是哪个文件的代码，请格式化一下再贴，或者指出哪个文件第几行，你应该是看错了吧，我记得是先发送IsMD5Exist请求，再上传文件的

**Comment by txcname** [comment]
刚刚查看，好像又是先发送的IsMD5Exist的这个请求， 然后后面的参数也有了md5value的参数。 谢谢！
