### ISSUE TITLE
关于 断点续传 POST http://localhost:9090/index/checkFileMd5 500错误的问题

### ISSUE THREAD

**Issue by qianhangkang** [izhangzhihao/FileUpload.Java#27]
# 断点续传前台出现 500 问题，后台出现空指针的问题

1. 环境：文件在uploads/{md5}/下有一个临时文件和conf文件（没有上传成功），redis数据库中只存在名字为FILE_UPLOAD_STATUS的Hash集合，当中存在一条记录key:{md5}，value:false。

2. 错误：
          前端控制台下：jquery.min.js:4 POST http://localhost:9090/index/checkFileMd5 500 ()
          后端控制台下：
java.lang.NullPointerException: null
at java.io.File.<init>(File.java:277)
at win.pangniu.learn.controller.IndexController.checkFileMd5(IndexController.java:61)....
          
3. 错误定位：
          代码：indexController.java
            ---->public Object checkFileMd5(String md5)
            ---->String value = stringRedisTemplate.opsForValue().get(Constants.FILE_MD5_KEY + md5);
          断点续传时，无法从redis数据库中拿到对应md5值文件的配置文件路径，即无法获取传了一半的配置文件路径，导致下面else中
                    File confFile = new File(value);的空指针异常
4. 解决方案：
           StorageServiceImpl.java文件的164行
`
 if (stringRedisTemplate.hasKey(Constants.FILE_MD5_KEY + param.getMd5())) {...}
`
PS：作者粗心逻辑写反了...
改为
`
 if (!stringRedisTemplate.hasKey(Constants.FILE_MD5_KEY + param.getMd5())) {...}
`
5. 结果：更改后经测验断点续传功能正常

**Comment by izhangzhihao** [comment]
你好像把 issue 提到了错误的repo，这个 repo 没有“StorageServiceImpl.java”这个文件。

**Comment by qianhangkang** [comment]
sry。。提交错了
